"""add description and logo_url to users

Revision ID: 3c839098f0a8
Revises: 221a55562aff
Create Date: 2026-07-21 10:18:07.491762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c839098f0a8'
down_revision: Union[str, Sequence[str], None] = '221a55562aff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'temps_conception')
    op.add_column('commandes', sa.Column('temps_conception', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commandes', 'temps_conception')
    op.add_column('clientes', sa.Column('temps_conception', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
