"""add description and logo_url to users

Revision ID: 6f453ba1be74
Revises: 3c839098f0a8
Create Date: 2026-07-21 10:22:47.836675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f453ba1be74'
down_revision: Union[str, Sequence[str], None] = '3c839098f0a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('logo_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'logo_url')
    op.drop_column('users', 'description')
    # ### end Alembic commands ###
